### ISSUE TITLE
Compatibility with composer 2.x

### ISSUE THREAD

**Issue by kissifrot** [Exercise/HTMLPurifierBundle#82] opened 2021-02-18 07:37 UTC
Hello,

When doing a composer install I'm getting the following warning:
```
Deprecation Notice: Class Exercise\HTMLPurifierBundle\Form\TypeExtension\ForwardCompatTypeExtensionTrait located in ./vendor/exercise/htmlpurifier-bundle/src/Form/TypeExtension/forward_compat_trait.inc.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Warning: Ambiguous class resolution, "Exercise\HTMLPurifierBundle\Form\TypeExtension\ForwardCompatTypeExtensionTrait" was found in both "/home/anonymous/app/vendor/exercise/htmlpurifier-bundle/src/Form/TypeExtension/forward_compat_trait.inc.php" and "/home/anonymous/app/vendor/exercise/htmlpurifier-bundle/src/Form/TypeExtension/ForwardCompatTypeExtensionTrait.php", the first will be used.
```

Can you fix psr-0 autoloading please?

**Comment by HeahDude** [comment] 2021-03-10 20:28
Hello @kissifrot, sorry for the late answer.

This is just a warning you can ignore. You can either upgrade to composer 2 without breaking anything, or update the bundle to 3.x so it does not use this include for BC anymore.

Closing here as this is not a bug or anything we can fix.

**Closed by HeahDude** 2021-03-10 20:28 UTC
